export const ADD_CATEGORY = "ADD_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const SET_CURRENT_CATEGORY = "SET_CURRENT_CATEGORY";
export const CLEAR_CURRENT_CATEGORY = "CLEAR_CURRENT_CATEGORY";

export const ADD_LOCATION = "ADD_LOCATION";
export const EDIT_LOCATION = "EDIT_LOCATION";
export const DELETE_LOCATION = "DELETE_LOCATION";
export const SET_CURRENT_LOCATION = "SET_CURRENT_LOCATION";
export const CLEAR_CURRENT_LOCATION = "CLEAR_CURRENT_LOCATION";

export const ADD_NEW_CATEGORY_TO_LOCATION = "ADD_NEW_CATEGORY_TO_LOCATION";
export const EDIT_CATEGORY_OF_LOCATION = "EDIT_CATEGORY_OF_LOCATION";
